// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Michel La Guardia",
            "url": "https://www.github.com/castmetal",
            "email": "mlaguardia@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/client": {
            "post": {
                "description": "Creating a client with route permissions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clients"
                ],
                "summary": "Create a client on args input",
                "parameters": [
                    {
                        "description": "CreateClient Data",
                        "name": "createClient",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateClientDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateClientResponseDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.CreateClientDTO": {
            "type": "object",
            "required": [
                "client_name",
                "key_period",
                "key_time_duration",
                "scope_name"
            ],
            "properties": {
                "client_name": {
                    "type": "string",
                    "minLength": 2
                },
                "id": {
                    "type": "string"
                },
                "key_period": {
                    "type": "string",
                    "minLength": 2
                },
                "key_time_duration": {
                    "type": "integer",
                    "minimum": 1
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Permission"
                    }
                },
                "scope_name": {
                    "type": "string",
                    "minLength": 2
                }
            }
        },
        "dtos.CreateClientResponseDTO": {
            "type": "object",
            "properties": {
                "api_id": {
                    "type": "string"
                },
                "client_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key_period": {
                    "type": "string"
                },
                "key_time_duration": {
                    "type": "integer"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Permission"
                    }
                },
                "scope_id": {
                    "type": "string"
                },
                "scope_name": {
                    "type": "string"
                }
            }
        },
        "dtos.Permission": {
            "type": "object",
            "properties": {
                "resource_method": {
                    "type": "string"
                },
                "resource_name": {
                    "type": "string"
                },
                "resource_path": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://localhost:8088",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Example API",
	Description:      "This is a sample server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
